### ISSUE TITLE
Rework external materializations to allow persistence

### ISSUE THREAD

**Issue by matsonj** [matsonj/nba-monte-carlo#102]
Currently, external materializations are basically a toy - they write parquet files into folders, but they only exist inside the environment during execution and then are flushed into the void. Furthermore, not all models that should be persisted this way are persisted! 

Options:
- use Motherduck to handle persistence between runs. CC @Alex-Monahan, this is a very interesting use case for duckDB + serverless analytics. Would love some thoughts about this. I am thinking "every job run outputs a unique file to motherduck" or something. My biggest concern is coupling to duckDB version since they are not backwards compatible.
- use serverless postgres (i.e. Neon) and write out resulting datasets to a persisted cache.
- write to S3/GCS/Azure Blob after each job run.
 - I tend to favor this approach because it is the most "generic" but the affordances of a real database (i.e. a catalog) are very nice.

**Comment by matsonj** [comment]
This would probably mean that "job runs" and "evidence builds" would need to be decoupled as well, but honestly, that makes sense because running the entire project every time will get too slow.

**Comment by Alex-Monahan** [comment]
Great question! In the medium term, MotherDuck will support time travel across changes to your database, so you should get that for free in the future. That work is ongoing but is a pretty big PR, so it will take a little while. 

In the meantime, the [sharing feature](https://motherduck.com/docs/motherduck-sql-reference/create-share) of MotherDuck may get you to where you want to go! If you create a share for each snapshot you want to take, it will create a copy of your database and persist it separately. You can then attach all your shares together for cross-snapshot comparisons. Would that work for what you are looking for? 

MotherDuck will handle the DuckDB storage version stuff for you. Before 1.0, we will do the migration on your behalf. After that, it should be seamless!

**Comment by matsonj** [comment]
Related conversation here: https://github.com/matsonj/nba-monte-carlo/issues/102

**Comment by matsonj** [comment]
@Alex-Monahan 👀
![image](https://github.com/matsonj/nba-monte-carlo/assets/16811433/4df45b12-19b7-49ec-949d-b87cacecb04d)

**Comment by Alex-Monahan** [comment]
> @Alex-Monahan 👀 ![image](https://private-user-images.githubusercontent.com/16811433/311554280-4df45b12-19b7-49ec-949d-b87cacecb04d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMjk2MjYsIm5iZiI6MTcxMDEyOTMyNiwicGF0aCI6Ii8xNjgxMTQzMy8zMTE1NTQyODAtNGRmNDViMTItMTliNy00OWVjLTk0OWQtYjg3Y2FjZWNiMDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDAzNTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMDJkOWY5Y2YzNzMxMDA0OTNkMmVhZGNlNWUzZWY1ZGMzMjhiNTA3ZmIxZmM0OTVhYzNlMDYyOWFkZjZkYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2T9BI1yTQ9tuWZ-Q9pKvjOozfXjmVP5kWFj5Bup9Kns)

Game on! Hit me up with any feedback, feature requests, or questions!
