### ISSUE TITLE
automate ingestion

### ISSUE THREAD

**Issue by matsonj** [matsonj/nba-monte-carlo#128]
currently i am updating by hand. need to figure out a way to get the csv sources updates w/python

**Comment by johalnes** [comment]
Was this previously done with the tap-spreadsheets-anywhere? I have seen you have done quite man changes to the meltano file. How is your experience with it? Is it worth to learn? 😄 

And about the ingestion, is it just a python script you are thinking about, or something like [Mage](https://docs.mage.ai/introduction/overview) or Dagster?

**Comment by matsonj** [comment]
Hi @johalnes - I have found meltano beneficial as it handles different python environments really well. The ingestion / ELT part of it is great when it works, but if you have any exceptions, it requires "real engineering" not data engineering. 

Anyway, the most important thing for me to automate ingestion is that its lightweight - so its unclear if I will care about things like state, rate limiting, and so on. I really like what they are up to with [dlt-hub](https://dlthub.com/), but I think v1 will probably be some simple scraping scripts on a few targets that don't worry about state, isn't particularly production-grade, but works great for my use case.

**Comment by johalnes** [comment]
Thanks for explaining a bit around Meltano. Makes sense 😊

I've been trying dlt hub a bit a while ago. I can play around a bit, and then you can take some inspiration if you'll like. What are the sources?

**Comment by matsonj** [comment]
Good question. Each model is made up of 3 sources:
- Hand curated win totals on which i run a regression analysis to find the initial elo rating for each team. This is static for the start of the season.
- The schedule for that sport (i.e. for nfl https://www.pro-football-reference.com/years/2023/games.htm) - this is mostly static although games can be rescheduled from time to time.
- The actual results, which are available along with schedule. This updates daily.

Since the model is so simple, i’ve been handling it by hand. But any help would be welcome!

**Comment by matsonj** [comment]
closed with #152
