### ISSUE TITLE
fix misc build issues

### ISSUE THREAD

**Issue by matsonj** [matsonj/nba-monte-carlo#161]
![image](https://github.com/matsonj/nba-monte-carlo/assets/16811433/04f14ebe-b9fb-4a84-a861-85cbe0ec6a9d)

looks like some old queries that need to get cleaned up + some type issues

**Comment by matsonj** [comment]
ref to `nba_elo` fixed! still seeing that error for null to FLOAT conversion, but not manifesting in the pages that I am seeing?

**Comment by rob-sokolowski** [comment]
Those warns seem to be percolating up. I ran (first time/fresh) things locally Sunday, I think things were ok? don't know for sure.

This screenshot is the site, not my local dev
![Screenshot from 2024-05-15 20-19-24](https://github.com/matsonj/nba-monte-carlo/assets/993431/b9549c04-3a1a-4283-ba82-1cf22bb9f8f0)

**Comment by matsonj** [comment]
That is correct - the model on sims the regular season only, so there is no data in the upcoming games table.

**Comment by matsonj** [comment]
I should add error handling on that though, I will take a look shortly and wrap it in a handle.

**Comment by matsonj** [comment]
Looks like this is also happening with the NFL model, which just got an update for the latest schedule.

**Comment by matsonj** [comment]
dropping a checklist of issues:

nba
- [x] home page, hide upcoming games if season is completed. return msg "regular season is completed" or something
- [x] advanced page, scatter plots are empty (hide them)
- [x] future predictions is broken, hide if the table is empty
- [x] nba team pages - upcoming schedule and lower should be hidden if the dataset is empty

ncaaf
- [x] team page score shows decimal places, i.e. 45.0 - 24.0

nfl
- [x] team pages show error in big value (handle?)
- [x] team pages show line charts + recent games, have error if season hasn't started yet. leave message like "will populate once season begins" or something
- [x] prediction page - hide detailed results, hide this if the relevant table is empty
