### ISSUE TITLE
db file not created

### ISSUE THREAD

**Issue by gregwdata** [matsonj/nba-monte-carlo#39]
Running from main branch in codespaces, follwed directions in `readme.md`, and was not able to connect to the db from superset.

Upon investigation, realized the file was not present at `/tmp/mdsbox.db` after running `make pipeline`.

![image](https://user-images.githubusercontent.com/79663385/202091113-8b47d8e4-b4c7-4017-b3d9-c6037c775952.png)

It looks like either the deletion of the `path` keys in profiles.yml in #33 , or that in combination with the switch to use external materialization in #36 is the cause. I have a PR incoming that I will link to this issue to add the `path` key back in that seems to fix it.

After doing that, the `mdsbox.db` file shows up for me:

![image](https://user-images.githubusercontent.com/79663385/202091729-95f0618f-ae4d-4f88-9ea3-d6adf89e980d.png)

**Comment by matsonj** [comment]
Hi @gregwdata, I’m actually going to adapt the [export.sql](https://github.com/matsonj/nba-monte-carlo/blob/master/transform/macros/export.sql) macro to export the database to that location after the dbt run completes. That functionality temporarily went away while I merged the ```--target parquet``` methodology into dbt properly once the ```external``` materialization was available.

If we separate the concerns this way, you can run the project without locking it inside of superset, since it can only be opened by one process at a time.

Does that work for you?

**Comment by gregwdata** [comment]
Totally fine with me. 

I actually started working a separate branch that effectively did that (I was creating separate .sql files to define a view for each final table and materialize to db, since I don't have the dbt macro chops). I noticed that just setting up that sql to materialize to a view didn't actually cause the db file to be written, though. When looking into why, noticed the dbt-duckdb readme note that a path field was required. Added that in, and that led to **all** the tables getting written to the db file (even though the default materialization for everything was "external", which I though might make it only go to parquet). Since that was sufficient, and kept things cleaner than adding sql files; I pivoted to just using the path approach.

Agree that limits the usage w/ locking of the db, though, so a clean db file build off of the output parquet from the dbt build makes sense. I'll be interested in seeing how you approach that with the export macro. Loop over all the parquet files in the output?

**Comment by gregwdata** [comment]
PS @matsonj, the problem of locking a db file is exactly something I had back of mind as a challenge on another application of duckdb - how to cleanly separate the ETL vs. the read-only usage of the tables downstream, so they can run concurrently. Really looking to see what best practice for doing that shapes up.

**Comment by matsonj** [comment]
@gregwdata I swear I had seen an EXPORT DATABASE which copied the current database to a new file, but what it does instead is write the data as csv/parquet and then script the SQL to rebuild it.

Anyway, there is a long discussion [over here](https://github.com/jwills/dbt-duckdb/issues/19). Right now it’s going toward parquet as the primary method, mainly for interoperability with other tools. At some point iceberg/delta table support will be added, which will be quite interesting, and of course, duckdb’s file format will mature to the point that it is most likely the preferred data format. 

On second thought, are you ok to use parquet with superset? Or do you require duckdb files? Trying to see if there is a compelling reason to use duckdb files.

**Comment by gregwdata** [comment]
LOL I had never used superset before, and was blindly following your readme
instructions to get acquainted with it when I ran into that issue. I’m
happy to try running it straight off the parquet files when I pick it back
up. I’m sure that won’t be a problem if superset has parquet read already
built in.
