### ISSUE TITLE
Superset Dashboard Files

### ISSUE THREAD

**Issue by n0012** [matsonj/nba-monte-carlo#43]
I ran the entire workflow within a VSCode devcontainer.  Cool stuff!  Do you have the Superset dashboard definitions uploaded to the repo (which produce the images in the readme?)

**Comment by matsonj** [comment]
No, they have to be configured manually in my testing. But the images are straight selects on the following tables: ```reg_season_summary``` and ```season_summary```. There is no data transformation happening in superset.

BTW I have some work in flight to get this working with evidence.dev and potentially rill developer.

**Comment by n0012** [comment]
Cool - [plotly dash](https://github.com/plotly/dash) could be an interesting option too.

**Comment by n0012** [comment]
Also here's the superset documentation for exporting/importing objects in order to quickly replicate that awesome looking boxplot for first timer superset users. https://superset.apache.org/docs/miscellaneous/importing-exporting-datasources/

**Comment by matsonj** [comment]
BTW a PR implementing plotly dash is more than welcome!!

**Comment by matsonj** [comment]
> Also here's the superset documentation for exporting/importing objects in order to quickly replicate that awesome looking boxplot for first timer superset users. https://superset.apache.org/docs/miscellaneous/importing-exporting-datasources/

Ok this looks excellent. I think I can rebuild those dashboards in the next few days and use the import/export functionality. Thank you for sharing!!

**Comment by matsonj** [comment]
@n0012 so I have this "working" but its only data sources & data sets. Which means, superset is still a deadend. Closing this one.

**Comment by matsonj** [comment]
https://github.com/andrewcstewart/ds4fnp/tree/main/superset#importing-and-exporting

```
# exports
superset export-datasources -f datasources.yml
superset export-dashboards -f dashboards.json

# imports
superset import-datasources -p datasources.yml
superset import-dashboards -p dashboards.json
```

**Comment by matsonj** [comment]
ok this is in now.

**Comment by n0012** [comment]
Thanks! Will give it a try
