### ISSUE TITLE
Project fails to build - TypeError: expected str, bytes or os.PathLike object, not tuple

### ISSUE THREAD

**Issue by matsonj** [matsonj/nba-monte-carlo#69]
Related issue: https://github.com/meltano/edk/issues/50

Meltano ```dbt-ext``` relies on the main branch of the ```edk```, so changes to either of those potentially break this project. 

Eventually these should be versioned and published on Pypl but for now it is a risk of the project

**Comment by matsonj** [comment]
FYI - all builds currently failing because of this issue.

**Comment by edgarrmondragon** [comment]
@matsonj The latest EDK should fix the `TypeError: expected str, bytes or os.PathLike object, not tuple` error if you want to give it a try

**Comment by matsonj** [comment]
Triggering this action: https://github.com/matsonj/nba-monte-carlo/actions/runs/3933351069

if it builds then I can close this issue

**Comment by matsonj** [comment]
@edgarrmondragon great success!
