### ISSUE TITLE
Getting error when running docker conatienr -> validate() got an unexpected keyword argument 'extra_validators'

### ISSUE THREAD

**Issue by akash-goel** [matsonj/nba-monte-carlo#72]
Hi Team,

we are trying to install the application on Ubuntu machine . we have followed the same procedure mentioned in the document .when we are running the docker image make using command "docker-run-superset" than getting below error.

![image](https://user-images.githubusercontent.com/5937612/214919257-812078a5-5d80-4aaf-8854-360898dd5361.png)

Can you please guide what we have to do to resolve this error .

Regards,
Akash

**Comment by matsonj** [comment]
@akash-goel I'm unable to replicate. What version of ubuntu are you running? by default I am running this in 20.04

**Comment by kidd** [comment]
I get the same issue.
I don't think ubuntu is relevant here, as I'm also running in a docker environment, and the error is the same.

"meltano.yml->utilities->superset" pins the versions of many libraries, but for superset it has a `>=1.5.0`, which afaik would allow pip to pick a different major version. I tried to change to `~=` but didn't work either, but I'm afraid I didn't cleanup the env correctly.

I'll try later this week when I've some time, but so far that's what I got.

**Comment by matsonj** [comment]
Oh yeah, superset might be on a new version. I can pin to 2.0. or to 1.6.2. let me take a look at this stuff.

**Comment by matsonj** [comment]
Interesting, I'm getting a 500 when running in the dev container (after authentication).

**Comment by matsonj** [comment]
It looks like 2.0.1 released on pypl in December, so it is possible that broke it. I'm pinning it to 2.0.0 and will see if that fixes it.

**Comment by matsonj** [comment]
So nothing to do with superset, I'm going to work back through the dependency chain on this one. paging @gregwdata since you pinned the dependencies on superset originally. It looks like something changed w/Flask.

**Comment by gregwdata** [comment]
Looks like we are seeing this issue: https://github.com/wtforms/flask-wtf/issues/547
Quick fix I'll look at is pinning an older version of flask-WTF, but longer term may need to look at how validate gets invoked on the superset login page and get it fixed there.

**Comment by matsonj** [comment]
Yep that worked! Thanks Greg!!
