### ISSUE TITLE
```npm run dev``` does not work in codespaces in evidence version 14.0.0

### ISSUE THREAD

**Issue by matsonj** [matsonj/nba-monte-carlo#81]
This used to work in evidence 10.0.0, but in the latest release, it does not. Will have to investigate. 

Current parameters are: 

```
evidence-run:
	cd analyze && npm run dev -- --host 0.0.0.0
```

**Comment by gregwdata** [comment]
Strange. I just tried a clean copy of your master branch in code spaces, and it worked. The only hitch was Codespaces didn't automatically pickup the port for forwarding, so had to manually add it to the ports list. I've seen Codespaces randomly do that before, so no idea if that's related. Are you getting an error message?

In case it helps, on the template repo, on the final update https://github.com/evidence-dev/template/pull/37 they added extra explicit dependencies to `package.json`.

      "dependencies": {
        "@evidence-dev/evidence": "14.0.0",
        "@evidence-dev/preprocess": "2.1.0",
        "@evidence-dev/components": "2.1.0"
      }

**Comment by matsonj** [comment]
Taking a look at it now.

**Comment by matsonj** [comment]
If I manually add port 3000 it works. So whatever the hook is to add the port to github is failing somewhere.
