### ISSUE TITLE
update to handle motherduck

### ISSUE THREAD

**Issue by matsonj** [matsonj/nba-monte-carlo#87]

**Comment by Alex-Monahan** [comment]
Woot! Following... 😄

**Comment by matsonj** [comment]
@Alex-Monahan can you poke internally for a key 😇

**Comment by Alex-Monahan** [comment]
> @Alex-Monahan can you poke internally for a key 😇

Happy to ask! Did you already apply for an invite on our site? https://motherduck.com/

**Comment by matsonj** [comment]
Yes I am in the queue!

**Comment by Alex-Monahan** [comment]
Invite sent! Let me know if you have any questions or issues. Psyched to see what you build and happy to help along the way!

**Comment by matsonj** [comment]
Ok small issue, from the [dbt-duckdb repo](https://github.com/jwills/dbt-duckdb):

> MotherDuck databases do not suppport transactions, so there is a new ```disable_transactions``` profile option that will be automatically enabled if you are connecting to a MotherDuck database in your path.

I am indeed using transactions to [calculate ELO changes](https://github.com/matsonj/nba-monte-carlo/blob/master/transform/macros/elo_rollforward.sql)  HOWEVER, it is deprecated and replaced in the ["v2" version](https://github.com/matsonj/mdsinabox) of this project. I suggest you follow along there, as I will handle it there.

**Comment by matsonj** [comment]
👀 👀 https://github.com/matsonj/nba-monte-carlo/blob/c34f53e91a131995a73c6c7b4715767b42f76477/evidence/package-lock.json#L3181-L3199
