### ISSUE TITLE
duckdb version issue on superset using docker

### ISSUE THREAD

**Issue by yeslawr2** [matsonj/nba-monte-carlo#90]
**Environment:** MacOS Ventura 13.4.1

**Command:** `make docker-run-superset`

**Description:** When I run the docker container for the superset visuals, I get the error shown below in the dashboard. I tried setting the duckdb-engine version to 0.7.1 in the [meltano.yml](https://github.com/matsonj/nba-monte-carlo/blob/master/meltano.yml#L68) file, but it still didn't work.
<img width="1698" alt="Screenshot 2023-07-24 at 12 18 49 PM" src="https://github.com/matsonj/nba-monte-carlo/assets/79434354/7522c7b9-54f4-4991-96ec-31aedcf6e487">

**Comment by matsonj** [comment]
Interesting. It looks like the version pinning in ```meltano.yml``` isn’t working, because it is set to ```duckdb-engine==0.6.8``` which I think is actually for duckdb 0.6.0. 

I’ll see if I can sort out the version pinning, but in the meantime, can you confirm what version of ```duckdb-engine``` is getting installed by meltano?

**Comment by matsonj** [comment]
Ok, so the issue is actually not anything to-do with ```duckdb-engine```, but rather that it has a dependency on ```duckdb```. So the fix is just pinning the duckdb version so it is the same in dbt + superset.

**Comment by matsonj** [comment]
Proof - running inside a codespace (on my iPad lol)

<img width="1194" alt="image" src="https://github.com/matsonj/nba-monte-carlo/assets/16811433/70a5b86f-c8fa-4f95-820f-348af9086212">

**Comment by yeslawr2** [comment]
That makes sense. Also, meltano installed duckdb 0.7.1 when I changed the value in the meltano.yml file. But looks like superset is able to connect to the db now. Thank you! 😃
