### ISSUE TITLE
Execute a python model

### ISSUE THREAD

**Issue by ReneTC** [matsonj/nba-monte-carlo#92]
This way of structing a data-stack in a box is just brilliant. I can get everything up and running except making a python model instead of a sql model.

I have this very basic py model to test:

```
import pandas as pd
def model(dbt, session):
    dbt.config(packages=["pandas"])
    data= dbt.ref("train_test_split")
    data['test_column'] = 1

    return data
```

However, upon a dbt:run I get:

```
Python model failed:
No module named 'pandas'
```

I consulted the author of duckdb-dbt [here](https://github.com/jwills/dbt-duckdb/issues/229), but I am still not able to run it. Is it possible in your end?

**Comment by ReneTC** [comment]
Works like a charm with [this tip ](https://github.com/jwills/dbt-duckdb/issues/229#issuecomment-1672643872)

**Comment by matsonj** [comment]
Yeah, python env management is annoying. Glad they were able to help you out! 

For future finders of this issue, meltano builds a separate env per plugin, so you need to include all dependencies in your meltano config.
